---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  issue-id:
    name: "JIRA ticket"
    runs-on: "ubuntu-latest"
    if: vars.ISSUE_ID_LOOKUP_JSON != ''
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: "Check/Add commit message JIRA ticket"
        # yamllint disable-line rule:line-length
        uses: ModeSevenIndustrialSolutions/issue-id/.github/actions/inject-issue-id-action@main
        with:
          issue_id_lookup_json: ${{ vars.ISSUE_ID_LOOKUP_JSON }}
