---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  issue-id:
    name: "JIRA ticket"
    runs-on: "ubuntu-latest"
    if: vars.ISSUE_ID_LOOKUP_JSON != ''
    permissions:
      contents: write
    # yamllint disable-line rule:line-length
    uses: ModeSevenIndustrialSolutions/issue-id/.github/workflows/reuse-issue-id.yaml@main
    with:
      issue_id_lookup_json: ${{ vars.ISSUE_ID_LOOKUP_JSON }}
